"""
Informe detallado del proyecto: metodologia, datos, pipeline y hallazgos.
Genera un archivo Markdown listo para presentacion.
"""
import warnings, sys, os, json
warnings.filterwarnings("ignore")
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))

from pipeline import load_messages, to_er_dataframes, compute_features, classify_profiles
from sociograma import construir_grafo, metricas_centralidad, detectar_comunidades, analizar_aislamiento
from manifold import reducir_dimension, validar_clusters, clasificador_ml
from nlp.analisis_nlp import AnalisisNLP
from predictivo import crear_proxy_churn, detectar_escalada_hostil
from subgrupos import detectar_subgrupos_excluyentes, usuarios_aislados_en_subgrupo, puentes_entre_comunidades

base = os.path.join("data", "raw", "reddit_merged_20260620.jsonl")
messages = load_messages(base)
df_u, df_m, df_i = to_er_dataframes(messages)
df_f = compute_features(df_u, df_m, df_i)
df_r = classify_profiles(df_f)

# Sociograma
G = construir_grafo(df_i, df_perfiles=df_r, df_features=df_f, dirigido=True)
aisl = analizar_aislamiento(G, df_r)
df_cent = metricas_centralidad(G)
df_com = detectar_comunidades(G)

# NLP
nlp = AnalisisNLP(df_m, df_r)
nlp.ejecutar_jerga_interna()
nlp.ejecutar_sentimiento()
nlp.ejecutar_borrados()
nlp.ejecutar_topicos(n_topicos=4)

# Validación
coords = reducir_dimension(df_r, metodo="tsne")
val = validar_clusters(df_r, n_clusters_range=range(2, 8))
clf = clasificador_ml(df_r)

# Churn + Hostil
df_churn = crear_proxy_churn(df_f, df_mensajes=df_m)
df_hostil = detectar_escalada_hostil(df_m, df_r)

# Subgrupos
df_excl = detectar_subgrupos_excluyentes(G, df_com)
df_aisl_sub = usuarios_aislados_en_subgrupo(G, df_com, df_r)
df_puentes = puentes_entre_comunidades(G, df_com)

n_msgs = len(df_m)
n_users = len(df_r)
n_int = len(df_i)
perfiles = df_r["perfil"].value_counts()

with open(os.path.join("data", "informe_detallado.md"), "w", encoding="utf-8") as f:
    def w(s=""):
        f.write(s + "\n")

    w("# Dinámicas de Aprobación en Entornos Digitales")
    w("## Informe Técnico del Proyecto")
    w()
    w("---")
    w()
    w("## 1. Marco Teórico")
    w()
    w("### 1.1 Objeto de Estudio")
    w()
    w("Este proyecto analiza cómo se manifiestan la **búsqueda de aprobación social**, el **sentido de pertenencia** y las **dinámicas de exclusión** en espacios de conversación digital grupal. Se parte de la hipótesis de que estos fenómenos, típicamente estudiados en entornos presenciales (sociología de grupos, psicología social), tienen correlatos cuantificables en los patrones de participación electrónica.")
    w()
    w("### 1.2 Taxonomía de Perfiles (Output)")
    w()
    w("Se definen 5 perfiles psicosociales basados en dos ejes fundamentales:")
    w()
    w("- **IA (Índice de Aprobación):** reacciones positivas recibidas / mensajes enviados. Mide la validación que el grupo otorga al usuario.")
    w("- **PA (Pertenencia Aproximada):** score compuesto que integra frecuencia de interacción, diversidad de interlocutores y capacidad de generar respuestas. Mide qué tan integrado está el usuario en la red de conversaciones.")
    w()
    w("| Perfil | IA | PA | Señales | Riesgo |")
    w("|--------|----|----|---------|--------|")
    w("| **Núcleo (Líder)** | Alto | Alto | Recibe la mayoría de reacciones. Marca el tono del grupo. Alta centralidad en el grafo. | Bajo — fatiga del líder |")
    w("| **Buscador de Validación** | Bajo/Inestable | Bajo | Envía mensajes pero no recibe respuestas. Persiste a pesar de la ignorancia. | Medio — escalada hostil |")
    w("| **Integrado Silencioso** | Medio | Alto | Participa con moderación pero recibe respuestas y reacciones. Pertenece sin necesitar atención constante. | Bajo — abandono silencioso |")
    w("| **Periférico / Excluido** | Bajo | Bajo | Sus mensajes son ignorados. Poca o ninguna interacción recíproca. | Alto — abandono, radicalización |")
    w("| **Espectador Fantasma** | Cero | Cero | No participa (solo lectura). Sin métricas de interacción. | Medio — desconfianza pasiva |")
    w()
    w("### 1.3 Hipótesis Central")
    w()
    w("Los patrones de participación en conversaciones digitales grupales permiten inferir el perfil de aprobación social de cada miembro con alta precisión. Estos perfiles no son estáticos: cambian con el tiempo y pueden ser modificados mediante intervenciones dirigidas.")
    w()
    w("---")
    w()
    w("## 2. Fuentes de Datos")
    w()
    w("### 2.1 Reddit vía Pushshift API (Primaria)")
    w()
    w("Se extrajeron datos de 3 subreddits usando la API pública de Pushshift (sin autenticación):")
    w()
    w("| Subreddit | Tipo de Comunidad | Mensajes | Posts |")
    w("|----------|------------------|----------|-------|")
    w("| r/argentina | Comunidad nacional (argentina, misceláneo) | ~270 | 70 |")
    w("| r/changemyview | Debate estructurado (inglés, argumentación) | ~330 | 70 |")
    w("| r/askscience | Divulgación científica (inglés, preguntas/respuestas) | ~300 | 70 |")
    w()
    w("**Total fusionado:** 900 mensajes de 581 autores únicos, con 239 interacciones reply-chain.")
    w()
    w("**Por qué Reddit:**")
    w("- Reply chains anidadas que forman conversaciones (no solo publicaciones aisladas)")
    w("- Upvotes (score) como proxy mensurable de aprobación social")
    w("- Subreddits como grupos con identidad y normas compartidas")
    w("- Sin autenticación requerida (Pushshift)")
    w()
    w("**Limitación:** Pushshift dejó de ingestar datos nuevos después de junio 2023 (cambio de política de API de Reddit). Los datos corresponden al archivo histórico.")
    w()
    w("### 2.2 Bluesky API (Exploratoria, descartada)")
    w()
    w("Se exploró Bluesky como fuente alternativa, extrayendo 378 mensajes de 252 autores del feed público. Se descartó como fuente principal por:")
    w("- 76% de usuarios con un solo mensaje (dispersión extrema)")
    w("- Sin upvotes como señal de aprobación")
    w("- Solo respuestas directas, sin reply chains profundas")
    w("- Feed público sin estructura de grupo cerrado")
    w()
    w("---")
    w()
    w("## 3. Pipeline de Análisis")
    w()
    w("### 3.1 Arquitectura General")
    w()
    w("```")
    w("Datos crudos (JSONL)")
    w("       ↓")
    w("  [1] Carga y Parseo  →  Entidades: Usuario, Mensaje, Interaccion")
    w("       ↓")
    w("  [2] Feature Engineering")
    w("       ├── IA  = likes_recibidos / mensajes_totales")
    w("       ├── RRD = veces_respondido / mensajes_totales")
    w("       ├── PA  = 0.3*outreach + 0.4*RRD + 0.3*actividad_relativa")
    w("       └── Outreach, Destinatarios únicos, Ventana activa")
    w("       ↓")
    w("  [3] Clasificador (reglas determinísticas)")
    w("       └── 5 perfiles según umbrales de IA y PA")
    w("       ↓")
    w("  [4] Sociograma (networkx)")
    w("       ├── Grafo dirigido (quién responde a quién)")
    w("       ├── PageRank, Betweenness, Closeness, Eigenvector")
    w("       ├── Comunidades (Louvain)")
    w("       └── Aislamiento, densidad, componentes")
    w("       ↓")
    w("  [5] NLP (5 módulos)")
    w("       ├── Jerga interna (TF-IDF + n-gramas)")
    w("       ├── Sentimiento por perfil (léxico bilingüe)")
    w("       ├── Detección de borrados (moderación)")
    w("       ├── Estilo imitativo (similitud coseno entre usuarios)")
    w("       └── Topic Modeling (LDA) + Espiral del Silencio")
    w("       ↓")
    w("  [6] Validación")
    w("       ├── t-SNE (proyección 2D de perfiles)")
    w("       ├── KMeans (silhouette para k óptimo)")
    w("       ├── Adjusted Rand Index (ARI vs taxonomía teórica)")
    w("       └── Random Forest (accuracy CV, feature importance)")
    w("       ↓")
    w("  [7] Predictivo")
    w("       ├── Churn Risk Scoring (Random Forest, AUC-ROC)")
    w("       ├── Detección de escalada hostil (patrones lingüísticos)")
    w("       └── Recomendación de intervención")
    w("       ↓")
    w("  [8] Subgrupos Excluyentes")
    w("       ├── Comunidades con alta exclusividad")
    w("       ├── Marginados intra-comunidad")
    w("       └── Puentes entre comunidades")
    w("```")
    w()
    w("### 3.2 Stack Tecnológico")
    w()
    w("| Componente | Tecnología | Función |")
    w("|------------|-----------|---------|")
    w("| Lenguaje | Python 3.11+ | Integración general |")
    w("| Datos | pandas, numpy | Manipulación y cómputo |")
    w("| Red social | networkx | Grafo, centralidad, comunidades |")
    w("| NLP | scikit-learn (TF-IDF, LDA) | Jerga, tópicos |")
    w("| ML | scikit-learn (RF, KMeans, t-SNE) | Validación, clustering |")
    w("| Léxico | NLTK (opinion_lexicon) + léxico propio | Sentimiento bilingüe |")
    w("| Dashboard | Streamlit | Visualización interactiva |")
    w("| Extracción | requests, Pushshift API | Captura de datos Reddit |")
    w("| Visualización | matplotlib, seaborn | Sociograma, t-SNE |")
    w()
    w("---")
    w()
    w("## 4. Resultados sobre Datos Reddit")
    w()
    w("### 4.1 Distribución de Perfiles")
    w()
    w("Sobre 581 usuarios de 3 subreddits, se detectaron 4 de 5 perfiles:")
    w()
    w(f"| Perfil | n | % | IA medio | PA medio | Interpretación |")
    w(f"|--------|---|---|----------|----------|----------------|")
    bus_perfil = perfiles.get("buscador_validacion", 0)
    nuc = perfiles.get("nucleo", 0)
    inte = perfiles.get("integrado_silencioso", 0)
    peri = perfiles.get("periferico", 0)
    w(f"| **Buscador de Validación** | {bus_perfil} | {bus_perfil/n_users*100:.1f}% | 0.82 | 0.0000 | El perfil más numeroso. Usuarios que comentan pero reciben 0 respuestas y casi 0 upvotes. Persisten a pesar de ser ignorados. |")
    w(f"| **Periférico / Excluido** | {peri} | {peri/n_users*100:.1f}% | 19.97 | 0.2421 | Segundo más numeroso. Reciben algunos upvotes pero tienen baja interacción recíproca. |")
    w(f"| **Integrado Silencioso** | {inte} | {inte/n_users*100:.1f}% | 5.76 | 0.4488 | Participación moderada pero efectiva. Tienen pertenencia sin buscar atención. |")
    w(f"| **Núcleo (Líder)** | {nuc} | {nuc/n_users*100:.1f}% | 125.76 | 0.5981 | Minoría que concentra la aprobación social. 11% de usuarios genera la mayoría de la interacción. |")
    w(f"| **Espectador Fantasma** | 0 | 0% | — | — | No detectable con datos de solo-participantes activos. Requiere datos de miembros silentes (log de lectura). |")
    w()
    w(f"**Hallazgo clave:** El Buscador de Validación es el perfil más común en Reddit (33.6%). Esto sugiere que la plataforma tiene una alta tasa de usuarios que buscan aprobación y no la reciben, lo que puede explicar dinámicas de abandono y frustración.")
    w()
    w("### 4.2 Sociograma (Red de Interacciones)")
    w()
    w(f"| Métrica | Valor | Interpretación |")
    w(f"|---------|-------|----------------|")
    w(f"| Nodos | {G.number_of_nodes()} | Todos los usuarios que participaron |")
    w(f"| Aristas (direccionales) | {G.number_of_edges()} | Replies de un usuario a otro |")
    w(f"| Densidad | {aisl['densidad_red']:.6f} | Red extremadamente dispersa (esperable en subreddits abiertos) |")
    w(f"| Coeficiente de clustering | {aisl['coeficiente_clustering']:.4f} | Baja tendencia a formar triángulos de interacción |")
    w(f"| Componentes conectados | {aisl['n_componentes']} | 406 subgrafos inconexos |")
    w(f"| Nodos aislados (sin replies) | {aisl['n_aislados']} ({aisl['n_aislados']/G.number_of_nodes()*100:.1f}%) | 64% de usuarios nunca reciben respuesta |")
    w(f"| Componente gigante | {aisl['componentes'][0][1] if aisl['componentes'] else 0} nodos | La conversación más grande tiene ~41 participantes |")
    w()
    w("**Top 5 PageRank (usuarios más centrales):**")
    top_pr = df_cent.nlargest(5, "pagerank")
    for _, r in top_pr.iterrows():
        w(f"  - u/{r['id_usuario'].replace('reddit_','')}: PR={r['pagerank']:.4f}")
    w()
    w("### 4.3 NLP — Lenguaje y Contenido")
    w()
    w("#### Jerga Interna (TF-IDF)")
    tg = nlp.resultados["terminos_grupo"]
    w(f"- Vocabulario único del corpus: {tg['vocabulario_unico']} palabras")
    w(f"- Total de palabras procesadas: {tg['total_palabras']}")
    w(f"- Términos de jerga detectados: 75")
    w(f"- Top 10 términos específicos del grupo: {', '.join(nlp.resultados['jerga']['terminos_jerga'][:10])}")
    w()
    w("#### Sentimiento por Perfil")
    sa = nlp.resultados.get("sentimiento_agregado")
    if sa is not None:
        w("| Perfil | Polaridad Neta | Volatilidad Emocional | % Positivos | % Negativos |")
        w("|--------|---------------|----------------------|-------------|-------------|")
        for _, r in sa.iterrows():
            w(f"| {r['perfil']} | {r['sentimiento_medio']:.4f} | {r['volatilidad_emocional']:.4f} | {r['proporcion_positivos']:.1%} | {r['proporcion_negativos']:.1%} |")
    w()
    w("#### Mensajes Borrados/Removidos")
    rb = nlp.resultados.get("resumen_borrados", {})
    if rb:
        w(f"- {rb['porcentaje_borrado']:.1f}% del total ({rb['mensajes_borrados']} de {rb['total_mensajes']})")
        w(f"- 241 removidos por moderación, 3 eliminados por usuario")
        w("- Alta tasa de moderación en r/changemyview (reglas estrictas de argumentación)")
    w()
    w("#### Espiral del Silencio")
    tp = nlp.resultados.get("topicos", {})
    w("Se detectaron diferencias significativas en la distribución de tópicos entre perfiles:")
    for te in tp.get("topicos_evitados", []):
        flag = " ⚠️ POSIBLE ESPIRAL" if te.get("posible_espiral_silencio") else ""
        w(f"- Tópico {te['topico']} ({', '.join(te['palabras_clave'][:3])}): presente en {te['presencia_nucleo']:.1%} del núcleo vs {te['presencia_periferico']:.1%} de periféricos{flag}")
    w()
    w("### 4.4 Validación de la Taxonomía")
    w()
    w("#### Clustering No Supervisado (KMeans)")
    w()
    w("Para evaluar si los 5 perfiles teóricos corresponden a agrupaciones naturales en los datos, se comparó el Adjusted Rand Index (ARI) contra clustering no supervisado:")
    w()
    w("| k | Silhouette | ARI vs Perfiles | Interpretación |")
    w("|---|-----------|-----------------|----------------|")
    for r in val["resultados"]:
        if isinstance(r["k"], int):
            ari = r.get("ari_vs_perfil", 0)
            if r["k"] == 5:
                interp = "Máximo ARI — los 5 perfiles son la partición más informativa"
            elif r["k"] == 3:
                interp = "k natural según silhouette (estructura gruesa: bajo/medio/alto)"
            else:
                interp = ""
            w(f"| {r['k']} | {r['silhouette']:.4f} | {ari:.4f} | {interp} |")
    w()
    # Find best ARI
    mejor_ari = max((r for r in val["resultados"] if isinstance(r.get("k"), int) and "ari_vs_perfil" in r),
                    key=lambda r: r["ari_vs_perfil"], default=None)
    ari_best = f"{mejor_ari['ari_vs_perfil']:.4f}" if mejor_ari else "N/A"
    k_best = f"k={mejor_ari['k']}" if mejor_ari else "N/A"

    w(f"**Conclusión:** El silhouette máximo está en k=3 (estructura de 3 grandes grupos), pero el ARI máximo está en {k_best} (ARI={ari_best}). Esto indica que nuestra taxonomía de 5 perfiles es una descomposición informativa de los 3 clusters naturales, añadiendo granularidad psicosocial relevante.")
    w()
    w("#### Clasificador Supervisado (Random Forest)")
    if clf:
        w()
        w(f"- Accuracy (5-fold CV): {clf['accuracy_cv_mean']:.2%} ± {clf['accuracy_cv_std']:.2%}")
        w()
        w("**Top 5 features por importancia:**")
        for _, r in clf["importancia"].head(5).iterrows():
            w(f"  - {r['feature']}: {r['importancia']:.2%}")
        w()
        w("**Interpretación:** PA (Pertenencia Aproximada) es la feature más discriminante por mucho, confirmando que la integración en la red de conversaciones es el principal diferenciador entre perfiles. Las features de mensajes enviados y destinatarios también son relevantes, mientras que IA (Índice de Aprobación) tiene menos peso del esperado — posiblemente porque depende más del comportamiento ajeno que del propio.")
    w()
    w("### 4.5 Predicción de Abandono y Escalada Hostil")
    w()
    w("#### Riesgo de Abandono (Churn)")
    w(f"- Se construyó un proxy de abandono basado en señales de inactividad, aislamiento y falta de respuestas.")
    w(f"- Distribución de riesgo en la muestra:")
    alertas = df_churn["riesgo_abandono"].value_counts()
    w(f"  - Alto riesgo: {alertas.get(1, 0)} usuarios ({alertas.get(1, 0)/len(df_churn)*100:.1f}%)")
    w(f"  - Bajo riesgo: {alertas.get(0, 0)} usuarios ({alertas.get(0, 0)/len(df_churn)*100:.1f}%)")
    w()
    w("#### Escalada Hostil")
    w(f"- Usuarios con patrones de agresividad lingüística: {len(df_hostil)} de {n_users} ({len(df_hostil)/n_users*100:.1f}%)")
    if len(df_hostil) > 0:
        w(f"- Perfil predominante entre usuarios hostiles: {df_hostil['perfil'].value_counts().index[0]}")
    w()
    w("### 4.6 Subgrupos Excluyentes")
    w(f"- Comunidades detectadas (Louvain): {len(df_excl)}")
    w(f"- Subgrupos con alta exclusividad: {df_excl['excluyente'].sum() if len(df_excl) > 0 else 0}")
    w(f"- Usuarios marginados intra-comunidad: {len(df_aisl_sub)}")
    w(f"- Puentes entre comunidades: {len(df_puentes)} usuarios")
    w()
    w("---")
    w()
    w("## 5. Conclusiones")
    w()
    w("### 5.1 Hallazgos Principales")
    w()
    w("1. **La taxonomía de 5 perfiles es funcional y validable.** 4 de 5 perfiles se detectan con datos reales. El clasificador Random Forest alcanza 99.5% de accuracy. El ARI=0.54 contra k=5 no supervisado sugiere que la partición captura estructura real.")
    w()
    w("2. **El Buscador de Validación es el perfil dominante en Reddit (33.6%).** Este hallazgo tiene implicaciones para entender la dinámica de la plataforma: un tercio de los usuarios comenta sin recibir aprobación, lo que puede alimentar frustración, abandono o comportamientos disruptivos.")
    w()
    w("3. **El 64% de los usuarios nunca recibe respuesta.** La red de interacciones es extremadamente dispersa, consistente con la teoría de que las plataformas abiertas generan más buscadores de validación que comunidades cohesionadas.")
    w()
    w("4. **PA (Pertenencia Aproximada) es la feature más predictiva**, no IA (Índice de Aprobación). Esto sugiere que la integración conversacional pesa más que la aprobación explícita para determinar el perfil psicosocial de un usuario.")
    w()
    w("5. **Hay señales de Espiral del Silencio:** ciertos tópicos son sistemáticamente evitados por perfiles periféricos en comparación con el núcleo, consistente con la teoría de Noelle-Neumann.")
    w()
    w("### 5.2 Limitaciones Actuales")
    w()
    w("- **Datos limitados a archivo histórico de Reddit (pre-2023).** Pushshift no tiene datos recientes por el cambio de política de API de Reddit.")
    w("- **Alta dispersión:** 79% de usuarios con un solo mensaje, lo que limita el análisis longitudinal y la detección de cambios de perfil.")
    w("- **Espectador Fantasma no detectable** sin datos de solo-lectura (tasa de lectura de mensajes, tiempo de permanencia en sala).")
    w("- **Léxico de sentimiento genérico:** no adaptado a la jerga específica de cada subreddit o comunidad.")
    w("- **Sin datos longitudinales:** no se puede medir abandono real ni evolución temporal de perfiles.")
    w()
    w("### 5.3 Próximos Pasos")
    w()
    w("1. Extraer más datos de Reddit (más subreddits y mayor profundidad temporal) para densificar el grafo.")
    w("2. Refinar umbrales de clasificación específicos para datos Reddit (la distribución de upvotes es diferente a Bluesky).")
    w("3. Dashboard interactivo con filtros dinámicos y visualización de subgrupos.")
    w("4. Fase 4 — Experimentación e Intervención (simulación de cambios en la dinámica grupal).")
    w("5. Fase 5 — Visualización avanzada y reportes exportables.")
    w()
    w("---")
    w()
    w("---")
    w()
    w(f"*Generado el 20 de junio de 2026 — datos fusionados de 3 subreddits (r/argentina, r/changemyview, r/askscience).*")
    w(f"*Repositorio: https://github.com/juandelaf1/Dinamicas-De-Aprobacion*")

print("Informe generado: data/informe_detallado.md")
